;; Defining a Clojure library that redefines some common sequence operations
;; with a consistent "main-problem-data" first argument order.
;;
;; Every public var below is generated by `consistent-lib.impl/defwrapper` from
;; two facts: the clojure.core fn being wrapped, and the permutation that moves
;; the collection to the front. Docstrings and :arglists are derived from the
;; wrapped var, so they cannot drift away from what clojure.core actually does.

(ns consistent-lib.core
  (:refer-clojure :exclude [partition partition-all partition-by take drop
                            take-nth take-while drop-while split-at split-with
                            group-by interleave interpose concat some remove
                            subvec reduce])
  (:require [consistent-lib.impl :refer [defwrapper]]))

(defwrapper partition
  [[coll n] [n coll]])

(defwrapper partition-all
  [[coll n] [n coll]])

(defwrapper partition-by
  [[coll f] [f coll]])

(defwrapper take
  [[coll n] [n coll]])

(defwrapper drop
  [[coll n] [n coll]])

(defwrapper take-nth
  [[coll n] [n coll]])

(defwrapper take-while
  [[coll pred] [pred coll]])

(defwrapper drop-while
  [[coll pred] [pred coll]])

(defwrapper split-at
  [[coll idx] [idx coll]])

(defwrapper split-with
  [[coll pred] [pred coll]])

(defwrapper group-by
  [[coll f] [f coll]])

(defwrapper interleave
  [[& colls] [colls]])

(defwrapper interpose
  [[coll separator] [separator coll]])

(defwrapper concat
  [[& colls] [colls]])

(defwrapper some
  [[coll pred] [pred coll]])

(defwrapper remove
  [[coll pred] [pred coll]])

(defwrapper subvec
  [[coll start end] [coll start end]])

(defwrapper reduce
  [[coll f]      [f coll]]
  [[coll f init] [f init coll]])

;; Example usage
(comment
  (partition [1 2 3 4 5 6] 2)
  ;;=> ((1 2) (3 4) (5 6))

  (take [1 2 3 4 5] 3)
  ;;=> (1 2 3)

  (group-by [1 2 3 4 5 6] odd?))
  ;;=> {true [1 3 5], false [2 4 6]}
